version: '3.1'
services:

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: notes-l10-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: notesl10
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      testing_l10_net:
        ipv4_address: 172.28.1.2

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: notes-l10-app-php-fpm
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app-php-fpm
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      testing_l10_net:
        ipv4_address: 172.28.1.1

  webserver:
    image: nginx:alpine
    container_name: notes-l10-app-webserver
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    networks:
      testing_l10_net:
        ipv4_address: 172.28.1.3

networks:
  testing_l10_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
#Volumes
volumes:
  dbdata:
    driver: local
